[package]
name = "typetag"
version = "0.2.1"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Serde serializable and deserializable trait objects"
repository = "https://github.com/dtolnay/typetag"
documentation = "https://docs.rs/typetag"
keywords = ["serde"]
categories = ["encoding"]
readme = "README.md"
edition = "2018"
rust-version = "1.62"

[workspace]
members = ["impl", "macro"]

[dependencies]
erased-serde = "0.3"
inventory = "0.3"
once_cell = "1.0"
serde = { version = "1.0", features = ["derive"] }
typetag-macro = { version = "=0.2.1", path = "macro" }

[dev-dependencies]
bincode = "1.0"
serde_json = "1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
